#!/usr/bin/env bash
set -x
cd ~/projects/llamafactory-practice/config || exit 1
cat > olmoe_qlora.yaml <<'EOF'
model_name_or_path: /home/simin/local_models/allenai/OLMoE-1B-7B-0125
trust_remote_code: true
compute_dtype: bfloat16
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1
quantization_bit: 4
quantization_method: bnb
quantization_type: nf4
double_quantization: true
dataset: identity_vm60
template: default
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 4
output_dir: /home/simin/projects/llamafactory-practice/saves/olmoe-qlora
logging_steps: 5
save_steps: 100
plot_loss: false
report_to: none
use_swanlab: true
swanlab_project: llamafactory-qlora-vm60
swanlab_mode: local
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100
EOF
cat > olmoe_lora.yaml <<'EOF'
model_name_or_path: /home/simin/local_models/allenai/OLMoE-1B-7B-0125
trust_remote_code: true
pure_bf16: true
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1
dataset: identity_vm60
template: default
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 4
output_dir: /home/simin/projects/llamafactory-practice/saves/olmoe-lora
logging_steps: 5
save_steps: 100
plot_loss: false
report_to: none
use_swanlab: true
swanlab_project: llamafactory-qlora-vm60
swanlab_mode: local
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
ddp_timeout: 180000000
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100
EOF
ls -la olmoe_*.yaml
echo CFG_DONE
